version: '3.7'
services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Tho2003@
      MYSQL_DATABASE: test_nestjs
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
    ports:
      - 3307:3307
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - chatapp
  phpMyadmin:
    container_name: test_app_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: Tho2003@
    ports:
      - 8080:80
    networks:
      - chatapp
    depends_on:
      - db
  be:
    container_name: test_app_be
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - chatapp
volumes:
  mysql-data:
networks:
  chatapp:
    driver: bridge
